# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 0.0.11
maven_group = com.github.mahmudindev.mcmod.worldportal
archives_name = worldportal
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.1

# Dependencies
fabric_loader_version = 0.16.14
fabric_api_version = 0.104.0+1.21.1
neoforge_version = 21.1.251

orenocommons_version = 0.0.9b+1.21.1
orenoevents_version = 0.0.4a+1.21.1
orenoconfig_version = 0.0.5+1.21.1
