architectury {
    common rootProject.enabled_platforms.split(',')
}

dependencies {
    // We depend on Fabric Loader here to use the Fabric @Environment annotations,
    // which get remapped to the correct annotations on each platform.
    // Do NOT use other classes from Fabric Loader.
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    modImplementation(
            group: "com.github.mahmudindev.mcmod.orenocommons",
            name: "orenocommons-common",
            version: rootProject.orenocommons_version
    )
    modImplementation(
            group: "com.github.mahmudindev.mcmod.orenoevents",
            name: "orenoevents-common",
            version: rootProject.orenoevents_version
    )
}
