modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/mahmudindev/mcmod-worldportal/issues"
license = "ARR"

[[mods]]
modId = "worldportal"
version = "${version}"
displayName = "World Portal"
authors = "mahmudindev"
description = '''
Create custom world portal to travel between dimensions.
'''
logoFile = "assets/worldportal/icon.png"

[[dependencies.worldportal]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.worldportal]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "worldportal.mixins.json"

["lithium:options"]
"mixin.ai.poi.fast_portals" = false
